#!/bin/sh
# Auto-generated by SessionStart hook (~/.claude/hooks/write-resume.sh).
# Usage:
#   ./resume.sh           resume the most recent session
#   ./resume.sh -l        list tracked sessions
#   ./resume.sh <prefix>  resume session whose id starts with <prefix>
# Tracked sessions (newest last):
# 2026-07-06 01:32  claude --resume db960d63-e878-4b78-8e78-adaedf6cc441
cd "$(dirname "$0")/.." || exit 1
ids=$(grep '^# 20' "$0" | awk '{print $NF}')
case "${1:-}" in
  -l|--list) grep '^# 20' "$0"; exit 0 ;;
  "") sid=$(printf '%s\n' "$ids" | tail -1) ;;
  *) sid=$(printf '%s\n' "$ids" | grep "^$1" | tail -1) ;;
esac
if [ -z "$sid" ]; then
  echo "resume.sh: no session matching '$1'; tracked sessions:" >&2
  grep '^# 20' "$0" >&2
  exit 1
fi
exec claude --resume "$sid"
