"""Map a provider SDK exception to a BackendError reason.

The openai and anthropic SDKs share an exception shape (both are generated by Stainless):
``APIStatusError`` carries ``status_code`` and the response; ``APITimeoutError`` is a kind of
``APIConnectionError``. Classifying by that shape, not by importing either SDK, keeps one
rule for every backend built on them.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from hardline.domain.errors import Reason


def classify(error: BaseException) -> tuple[Reason, float | None]:
    """``(reason, retry_after_seconds)`` for a provider exception."""
    names = {cls.__name__ for cls in type(error).__mro__}
    if "APITimeoutError" in names:
        return "timeout", None
    if "APIConnectionError" in names:
        return "unavailable", None
    status = getattr(error, "status_code", None)
    if not isinstance(status, int):
        return "unknown", None
    retry_after = _retry_after(error)
    if status in (401, 403):
        return "auth", None
    if status == 429:
        return "rate_limit", retry_after
    if status == 408:
        return "timeout", retry_after
    if status >= 500:  # includes Anthropic's 529 overloaded
        return "unavailable", retry_after
    if 400 <= status < 500:
        return "bad_request", None
    return "unknown", None


def _retry_after(error: BaseException) -> float | None:
    response = getattr(error, "response", None)
    headers = getattr(response, "headers", None)
    if headers is None:
        return None
    value = headers.get("retry-after")
    try:
        return max(0.0, float(value)) if value is not None else None
    except (TypeError, ValueError):
        return None  # an HTTP-date form; the runtime's own backoff applies
